### PR TITLE
Dealers CRUD: Index

### PR DESCRIPTION
**Pull request by mtopete1996**
## Quick Info
Creates Index for Dealer's model.

## What does this change?
Adds:
- Dealer's model, migration, and controller for dealers.
- Install Bootstrap 4 and FontAwesome 5
- Adds the REST routes for Dealers
- Adds the index view of Dealers

## How do you manually test this?
Go to /dealers

## Screenshots
image

### CODE REVIEW

**Review by fabiannabi — APPROVED** [review]
~LGTM 
It looks really nice Good Job!

**Review by AlanAnguiano — APPROVED** [review]
LGTM

**Review by hugooSoul — APPROVED** [review]
LGTM

**Review by fabiannabi — APPROVED** [review]

**Review by hugooSoul — APPROVED** [review]
LGTM

**Pull request merged**
